[2024-04-13T14:58:10.121-0400] {processor.py:161} INFO - Started process (PID=29961) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T14:58:10.122-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T14:58:10.122-0400] {logging_mixin.py:188} INFO - [2024-04-13T14:58:10.122-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T14:58:10.162-0400] {logging_mixin.py:188} INFO - [2024-04-13T14:58:10.161-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T14:58:10.162-0400] {logging_mixin.py:188} INFO - [2024-04-13T14:58:10.162-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T14:58:10.162-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T14:58:10.188-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-13T14:59:39.072-0400] {processor.py:161} INFO - Started process (PID=30053) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T14:59:39.072-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T14:59:39.073-0400] {logging_mixin.py:188} INFO - [2024-04-13T14:59:39.072-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T14:59:39.113-0400] {logging_mixin.py:188} INFO - [2024-04-13T14:59:39.113-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T14:59:39.113-0400] {logging_mixin.py:188} INFO - [2024-04-13T14:59:39.113-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T14:59:39.113-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T14:59:39.139-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-04-13T15:01:35.604-0400] {processor.py:161} INFO - Started process (PID=30162) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:01:35.605-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T15:01:35.606-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:01:35.606-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:01:35.645-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:01:35.645-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T15:01:35.646-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:01:35.646-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T15:01:35.646-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:01:35.671-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-13T15:03:31.938-0400] {processor.py:161} INFO - Started process (PID=30263) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:03:31.938-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T15:03:31.938-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:03:31.938-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:03:31.978-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:03:31.978-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T15:03:31.978-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:03:31.978-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T15:03:31.978-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:03:32.004-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-13T15:05:32.094-0400] {processor.py:161} INFO - Started process (PID=30388) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:05:32.095-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T15:05:32.096-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:05:32.096-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:05:32.137-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:05:32.136-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T15:05:32.137-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:05:32.137-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T15:05:32.137-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:05:32.164-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2024-04-13T15:07:32.938-0400] {processor.py:161} INFO - Started process (PID=30542) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:07:32.939-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T15:07:32.939-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:07:32.939-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:07:32.982-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:07:32.982-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T15:07:32.982-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:07:32.982-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T15:07:32.982-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:07:33.008-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-04-13T15:14:46.576-0400] {processor.py:161} INFO - Started process (PID=30737) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:14:46.577-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T15:14:46.577-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:14:46.577-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:14:46.617-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:14:46.616-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T15:14:46.617-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:14:46.617-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T15:14:46.617-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:14:46.642-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-04-13T15:16:44.633-0400] {processor.py:161} INFO - Started process (PID=30855) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:16:44.633-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T15:16:44.634-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:16:44.634-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:16:44.672-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:16:44.672-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T15:16:44.672-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:16:44.672-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T15:16:44.672-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:16:44.698-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-13T15:28:49.990-0400] {processor.py:161} INFO - Started process (PID=31042) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:28:49.991-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T15:28:49.991-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:28:49.991-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:28:50.030-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:28:50.030-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T15:28:50.030-0400] {logging_mixin.py:188} INFO - [2024-04-13T15:28:50.030-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T15:28:50.030-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T15:28:50.055-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-04-13T17:52:58.646-0400] {processor.py:161} INFO - Started process (PID=31209) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T17:52:58.647-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T17:52:58.647-0400] {logging_mixin.py:188} INFO - [2024-04-13T17:52:58.647-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T17:52:58.688-0400] {logging_mixin.py:188} INFO - [2024-04-13T17:52:58.687-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T17:52:58.688-0400] {logging_mixin.py:188} INFO - [2024-04-13T17:52:58.688-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T17:52:58.688-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T17:52:58.713-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-04-13T18:20:02.123-0400] {processor.py:161} INFO - Started process (PID=31350) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T18:20:02.123-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T18:20:02.124-0400] {logging_mixin.py:188} INFO - [2024-04-13T18:20:02.124-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T18:20:02.161-0400] {logging_mixin.py:188} INFO - [2024-04-13T18:20:02.161-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T18:20:02.161-0400] {logging_mixin.py:188} INFO - [2024-04-13T18:20:02.161-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T18:20:02.161-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T18:20:02.187-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-04-13T19:02:12.835-0400] {processor.py:161} INFO - Started process (PID=31486) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T19:02:12.836-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T19:02:12.837-0400] {logging_mixin.py:188} INFO - [2024-04-13T19:02:12.837-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T19:02:12.882-0400] {logging_mixin.py:188} INFO - [2024-04-13T19:02:12.881-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T19:02:12.882-0400] {logging_mixin.py:188} INFO - [2024-04-13T19:02:12.882-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T19:02:12.882-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T19:02:12.911-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2024-04-13T19:10:52.182-0400] {processor.py:161} INFO - Started process (PID=31569) to work on /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T19:10:52.183-0400] {processor.py:830} INFO - Processing file /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-13T19:10:52.183-0400] {logging_mixin.py:188} INFO - [2024-04-13T19:10:52.183-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T19:10:52.226-0400] {logging_mixin.py:188} INFO - [2024-04-13T19:10:52.225-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-13T19:10:52.226-0400] {logging_mixin.py:188} INFO - [2024-04-13T19:10:52.226-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-13T19:10:52.226-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-13T19:10:52.252-0400] {processor.py:183} INFO - Processing /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
