[2024-04-15T20:52:36.447-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T20:52:36.483-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-15T20:52:36.491-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-15T20:52:36.491-0400] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T20:52:36.499-0400] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): bash_task> on 2024-04-15 00:00:00+00:00
[2024-04-15T20:52:36.503-0400] {standard_task_runner.py:63} INFO - Started process 53675 to run task
[2024-04-15T20:52:36.508-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_dag', 'bash_task', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/preprocessing_dag.py', '--cfg-path', '/var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T/tmpw7u9r71a']
[2024-04-15T20:52:36.511-0400] {standard_task_runner.py:91} INFO - Job 271: Subtask bash_task
[2024-04-15T20:52:36.561-0400] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_dag.bash_task scheduled__2024-04-15T00:00:00+00:00 [running]> on host manis-macbook-air.local
[2024-04-15T20:52:36.608-0400] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='preprocessing_dag' AIRFLOW_CTX_TASK_ID='bash_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-15T20:52:36.609-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T20:52:36.648-0400] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T
[2024-04-15T20:52:36.649-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/cap_dbt && dbt run']
[2024-04-15T20:52:36.656-0400] {subprocess.py:86} INFO - Output:
[2024-04-15T20:52:38.945-0400] {subprocess.py:93} INFO - [0m00:52:38  Running with dbt=1.7.11
[2024-04-15T20:52:40.227-0400] {subprocess.py:93} INFO - [0m00:52:40  Registered adapter: snowflake=1.7.3
[2024-04-15T20:52:40.398-0400] {subprocess.py:93} INFO - [0m00:52:40  Found 3 models, 1 source, 0 exposures, 0 metrics, 544 macros, 0 groups, 0 semantic models
[2024-04-15T20:52:40.399-0400] {subprocess.py:93} INFO - [0m00:52:40
[2024-04-15T20:52:41.692-0400] {subprocess.py:93} INFO - [0m00:52:41  Concurrency: 1 threads (target='dev')
[2024-04-15T20:52:41.694-0400] {subprocess.py:93} INFO - [0m00:52:41
[2024-04-15T20:52:41.695-0400] {subprocess.py:93} INFO - [0m00:52:41  1 of 3 START sql view model DEV.raw_data_processing ............................ [RUN]
[2024-04-15T20:52:42.184-0400] {subprocess.py:93} INFO - [0m00:52:42  1 of 3 OK created sql view model DEV.raw_data_processing ....................... [[32mSUCCESS 1[0m in 0.49s]
[2024-04-15T20:52:42.185-0400] {subprocess.py:93} INFO - [0m00:52:42  2 of 3 START sql view model DEV.flatten ........................................ [RUN]
[2024-04-15T20:52:42.646-0400] {subprocess.py:93} INFO - [0m00:52:42  2 of 3 OK created sql view model DEV.flatten ................................... [[32mSUCCESS 1[0m in 0.46s]
[2024-04-15T20:52:42.648-0400] {subprocess.py:93} INFO - [0m00:52:42  3 of 3 START sql table model DEV.aggregation ................................... [RUN]
[2024-04-15T20:52:42.728-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-15T20:52:42.735-0400] {process_utils.py:132} INFO - Sending 15 to group 53675. PIDs of all processes in the group: [53676, 53677, 53680, 53675]
[2024-04-15T20:52:42.735-0400] {process_utils.py:87} INFO - Sending the signal 15 to group 53675
[2024-04-15T20:52:42.736-0400] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-15T20:52:42.736-0400] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-04-15T20:52:42.738-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T20:52:42.744-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=53677, status='terminated', started='20:52:36') (53677) terminated with exit code None
[2024-04-15T20:52:42.752-0400] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-04-15T20:52:42.760-0400] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocessing_dag, task_id=bash_task, execution_date=20240415T000000, start_date=20240416T005236, end_date=20240416T005242
[2024-04-15T20:52:42.808-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=53675, status='terminated', exitcode=2, started='20:52:36') (53675) terminated with exit code 2
[2024-04-15T20:52:42.808-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=53676, status='terminated', started='20:52:36') (53676) terminated with exit code None
[2024-04-15T20:52:42.808-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=53680, status='terminated', started='20:52:40') (53680) terminated with exit code None
